name: Unikernels
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Extract the branch name
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
      -
        name: Set the commit used for the opam repository
        run: echo "COMMIT_OPAM_REPOSITORY=c03ceac6872a8ff0ebed2c4fa28b0013fb1984e2"
      -
        name: Build relay
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BRANCH=${{ env.BRANCH }}
            COMMIT_OPAM_REPOSITORY=${{ env.COMMIT_OPAM_REPOSITORY }}
          tags: mirage/ptt:${{ env.BRANCH }}
          file: ./Dockerfile.relay
      -
        name: Build submission
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BRANCH=${{ env.BRANCH }}
            COMMIT_OPAM_REPOSITORY=${{ env.COMMIT_OPAM_REPOSITORY }}
          file: ./Dockerfile.submission
      -
        name: Build signer
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BRANCH=${{ env.BRANCH }}
            COMMIT_OPAM_REPOSITORY=${{ env.COMMIT_OPAM_REPOSITORY }}
          file: ./Dockerfile.signer
      -
        name: Build spamfilter
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BRANCH=${{ env.BRANCH }}
            COMMIT_OPAM_REPOSITORY=${{ env.COMMIT_OPAM_REPOSITORY }}
          file: ./Dockerfile.spamfilter
      -
        name: Build verifier
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            BRANCH=${{ env.BRANCH }}
            COMMIT_OPAM_REPOSITORY=${{ env.COMMIT_OPAM_REPOSITORY }}
          file: ./Dockerfile.verifier
